import type { CharacterProject } from '../../schema/types.js';

export function exportToGDScript(project: CharacterProject): string {
  const lines: string[] = [
    `# Generated by NStep Code Motion`,
    `# Project: ${project.name}`,
    `extends Node2D`,
    ``,
    `var time: float = 0.0`,
    ``
  ];

  lines.push(`func _ready():`, `\tpass`, ``);
  lines.push(`func _process(delta: float):`, `\ttime += delta`);

  project.parts.forEach(part => {
    const varName = part.name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
    lines.push(`\t# Update ${part.name}`);
    lines.push(`\tvar ${varName}_node = get_node_or_null("${part.name}")`);
    lines.push(`\tif ${varName}_node:`);

    const anim = project.animations[0];
    if (anim) {
      const controllers = anim.controllers.filter(c => c.targetPartId === part.id && c.enabled);
      controllers.forEach(ctrl => {
        const { speed, amplitude, phase, offset } = ctrl.params;
        const formula = `sin(time * ${speed.toFixed(2)} * TAU + ${phase.toFixed(2)}) * ${amplitude.toFixed(2)} + ${offset.toFixed(2)}`;
        switch (ctrl.property) {
          case 'x':
            lines.push(`\t\t${varName}_node.position.x = ${part.baseX.toFixed(2)} + ${formula}`);
            break;
          case 'y':
            lines.push(`\t\t${varName}_node.position.y = ${part.baseY.toFixed(2)} + ${formula}`);
            break;
          case 'rotation':
            lines.push(`\t\t${varName}_node.rotation_degrees = ${part.baseRotation.toFixed(2)} + ${formula}`);
            break;
          case 'scaleX':
            lines.push(`\t\t${varName}_node.scale.x = ${part.baseScaleX.toFixed(2)} + ${formula}`);
            break;
          case 'scaleY':
            lines.push(`\t\t${varName}_node.scale.y = ${part.baseScaleY.toFixed(2)} + ${formula}`);
            break;
          default:
            break;
        }
      });
      if (controllers.length === 0) {
        lines.push(`\t\tpass`);
      }
    } else {
      lines.push(`\t\tpass`);
    }
  });

  return lines.join('\n');
}
